name: loogbook_mobile_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.2
  change_notifier: ^0.24.0
  table_calendar: ^3.0.4
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
